import * as AuthSession from 'expo-auth-session'; import * as WebBrowser from 'expo-web-browser';
import { router, Stack } from 'expo-router'; import { useEffect, useState } from 'react'; import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { authConfigFromEnv } from '../src/auth/config'; import { tokenSetFromExchange } from '../src/auth/sessionManager'; import { useApp } from '../src/session/AppContext'; import { colors } from '../src/ui/theme';
WebBrowser.maybeCompleteAuthSession();
export default function Login() { const config = authConfigFromEnv(); return config.devBypass ? <DemoLogin /> : config.issuer && config.clientId ? <OidcLogin issuer={config.issuer} clientId={config.clientId} /> : <LoginShell><View style={styles.card}><Text style={styles.error}>Configuração OIDC obrigatória ausente.</Text></View></LoginShell>; }
function OidcLogin({ issuer, clientId }: { issuer: string; clientId: string }) {
  const { completeOidcLogin } = useApp(); const [error, setError] = useState<string>(); const discovery = AuthSession.useAutoDiscovery(issuer); const redirectUri = AuthSession.makeRedirectUri({ scheme: 'naplog', path: 'oauth' });
  const [request, response, prompt] = AuthSession.useAuthRequest({ clientId, responseType: AuthSession.ResponseType.Code, redirectUri, scopes: ['openid', 'profile', 'offline_access'], usePKCE: true }, discovery);
  useEffect(() => { if (response?.type !== 'success' || !discovery || !request?.codeVerifier || !clientId) return; void (async () => { try { const exchanged = await AuthSession.exchangeCodeAsync({ clientId, code: response.params.code, redirectUri, extraParams: { code_verifier: request.codeVerifier! } }, discovery); await completeOidcLogin(tokenSetFromExchange(exchanged)); router.replace('/journey'); } catch { setError('Não foi possível concluir a autenticação.'); } })(); }, [response, discovery, request?.codeVerifier, clientId]);
  const configured = true;
  return <LoginShell><View style={styles.card}><Text style={styles.copy}>{configured ? 'Entre com sua conta corporativa.' : 'Configuração OIDC obrigatória ausente.'}</Text>{error && <Text style={styles.error}>{error}</Text>}<Pressable disabled={!configured || !request} style={[styles.button, (!configured || !request) && styles.disabled]} onPress={() => void prompt()}><Text style={styles.buttonText}>Entrar com Keycloak</Text></Pressable></View></LoginShell>;
}
function DemoLogin() { const { demoLogin } = useApp(); return <LoginShell><View style={styles.card}><Text style={styles.dev}>BYPASS EXCLUSIVO DE DESENVOLVIMENTO</Text><Text style={styles.label}>E-mail</Text><TextInput style={styles.input} autoCapitalize="none" defaultValue="motorista@demo.com" /><Pressable style={styles.button} onPress={() => { demoLogin(); router.replace('/journey'); }}><Text style={styles.buttonText}>Entrar na demonstração</Text></Pressable></View></LoginShell>; }
function LoginShell({ children }: { children: React.ReactNode }) { return <View style={styles.page}><Stack.Screen options={{ headerShown: false }} /><View><Text style={styles.eyebrow}>NAP LOG</Text><Text style={styles.title}>Sua operação, em movimento.</Text></View>{children}</View>; }
const styles = StyleSheet.create({ page: { flex: 1, padding: 24, paddingTop: 100, justifyContent: 'space-between', backgroundColor: colors.background }, eyebrow: { color: colors.primary, fontWeight: '800', letterSpacing: 3 }, title: { color: colors.ink, fontSize: 38, fontWeight: '800', lineHeight: 44, marginTop: 14 }, copy: { color: colors.muted, fontSize: 16, marginBottom: 18 }, card: { backgroundColor: colors.surface, borderRadius: 24, padding: 20, marginBottom: 24 }, label: { color: colors.ink, fontWeight: '600', marginBottom: 7 }, input: { borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 14, marginBottom: 16, fontSize: 16 }, button: { backgroundColor: colors.primary, padding: 16, borderRadius: 13, alignItems: 'center' }, disabled: { opacity: .45 }, buttonText: { color: 'white', fontWeight: '800', fontSize: 16 }, dev: { color: '#8A5B00', fontWeight: '800', fontSize: 11, marginBottom: 18 }, error: { color: colors.danger, marginBottom: 12 } });
