CREATE EXTENSION IF NOT EXISTS "postgis";
CREATE TYPE "activity_status" AS ENUM ('draft','awaiting_assignment','assigned','accepted','en_route','near_destination','on_site','in_service','completed','failed','rescheduled','canceled','returned');
CREATE TABLE "tenants" ("id" UUID PRIMARY KEY, "name" VARCHAR(160) NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "companies" ("id" UUID PRIMARY KEY, "tenant_id" UUID NOT NULL, "name" VARCHAR(160) NOT NULL, "tax_id" VARCHAR(32), CONSTRAINT "companies_tenant_fk" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT);
CREATE UNIQUE INDEX "companies_tenant_id_id_key" ON "companies"("tenant_id","id");
CREATE UNIQUE INDEX "companies_tenant_tax_key" ON "companies"("tenant_id","tax_id");
CREATE TABLE "branches" ("id" UUID PRIMARY KEY, "tenant_id" UUID NOT NULL, "company_id" UUID NOT NULL, "name" VARCHAR(160) NOT NULL, "code" VARCHAR(60) NOT NULL, CONSTRAINT "branches_company_fk" FOREIGN KEY ("tenant_id","company_id") REFERENCES "companies"("tenant_id","id") ON DELETE RESTRICT);
CREATE UNIQUE INDEX "branches_tenant_id_id_key" ON "branches"("tenant_id","id");
CREATE UNIQUE INDEX "branches_code_key" ON "branches"("tenant_id","company_id","code");
CREATE TABLE "users" ("id" UUID PRIMARY KEY, "tenant_id" UUID NOT NULL REFERENCES "tenants"("id"), "company_id" UUID, "branch_id" UUID, "external_id" VARCHAR(160) NOT NULL, "email" VARCHAR(254) NOT NULL, "display_name" VARCHAR(160) NOT NULL);
CREATE UNIQUE INDEX "users_external_key" ON "users"("tenant_id","external_id");
CREATE UNIQUE INDEX "users_email_key" ON "users"("tenant_id","email");
ALTER TABLE "users" ADD CONSTRAINT "users_company_fk" FOREIGN KEY ("tenant_id","company_id") REFERENCES "companies"("tenant_id","id") ON DELETE RESTRICT;
ALTER TABLE "users" ADD CONSTRAINT "users_branch_fk" FOREIGN KEY ("tenant_id","branch_id") REFERENCES "branches"("tenant_id","id") ON DELETE RESTRICT;
CREATE TABLE "drivers" ("id" UUID PRIMARY KEY, "tenant_id" UUID NOT NULL REFERENCES "tenants"("id"), "company_id" UUID NOT NULL, "name" VARCHAR(160) NOT NULL, "document" VARCHAR(120), CONSTRAINT "drivers_company_fk" FOREIGN KEY ("tenant_id","company_id") REFERENCES "companies"("tenant_id","id"));
CREATE UNIQUE INDEX "drivers_tenant_id_id_key" ON "drivers"("tenant_id","id");
CREATE TABLE "vehicles" ("id" UUID PRIMARY KEY, "tenant_id" UUID NOT NULL REFERENCES "tenants"("id"), "company_id" UUID NOT NULL, "plate" VARCHAR(16) NOT NULL, CONSTRAINT "vehicles_company_fk" FOREIGN KEY ("tenant_id","company_id") REFERENCES "companies"("tenant_id","id"));
CREATE UNIQUE INDEX "vehicles_plate_key" ON "vehicles"("tenant_id","plate");
CREATE TABLE "activities" ("id" UUID PRIMARY KEY, "tenant_id" UUID NOT NULL REFERENCES "tenants"("id"), "company_id" UUID, "branch_id" UUID, "external_reference" VARCHAR(120), "description" VARCHAR(500) NOT NULL, "address" VARCHAR(500) NOT NULL, "destination" geography(Point,4326), "status" "activity_status" NOT NULL DEFAULT 'awaiting_assignment', "version" INTEGER NOT NULL DEFAULT 1, "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMPTZ(3) NOT NULL);
CREATE UNIQUE INDEX "activities_tenant_id_id_key" ON "activities"("tenant_id","id");
CREATE UNIQUE INDEX "activities_external_key" ON "activities"("tenant_id","external_reference");
CREATE INDEX "activities_status_idx" ON "activities"("tenant_id","status","updated_at");
CREATE INDEX "activities_destination_gist" ON "activities" USING GIST ("destination");
ALTER TABLE "activities" ADD CONSTRAINT "activities_company_fk" FOREIGN KEY ("tenant_id","company_id") REFERENCES "companies"("tenant_id","id") ON DELETE RESTRICT;
ALTER TABLE "activities" ADD CONSTRAINT "activities_branch_fk" FOREIGN KEY ("tenant_id","branch_id") REFERENCES "branches"("tenant_id","id") ON DELETE RESTRICT;
CREATE TABLE "assignments" ("id" UUID PRIMARY KEY, "tenant_id" UUID NOT NULL REFERENCES "tenants"("id"), "activity_id" UUID NOT NULL, "driver_id" UUID NOT NULL, "assigned_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "ended_at" TIMESTAMPTZ(3), FOREIGN KEY ("tenant_id","activity_id") REFERENCES "activities"("tenant_id","id"), FOREIGN KEY ("tenant_id","driver_id") REFERENCES "drivers"("tenant_id","id"));
CREATE UNIQUE INDEX "assignments_one_active" ON "assignments"("tenant_id","activity_id") WHERE "ended_at" IS NULL;
CREATE TABLE "activity_events" ("id" UUID PRIMARY KEY, "tenant_id" UUID NOT NULL REFERENCES "tenants"("id"), "activity_id" UUID NOT NULL, "type" VARCHAR(80) NOT NULL, "payload" JSONB NOT NULL, "occurred_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("tenant_id","activity_id") REFERENCES "activities"("tenant_id","id"));
CREATE INDEX "activity_events_timeline_idx" ON "activity_events"("tenant_id","activity_id","occurred_at");
