"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { fleetApi } from "@/lib/api";
import type { DriverRecord, VehicleRecord } from "@/lib/types";

export default function DriversPage(){
 const [drivers,setDrivers]=useState<DriverRecord[]>([]),[vehicles,setVehicles]=useState<VehicleRecord[]>([]);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string>(),[notice,setNotice]=useState<string>();
 const load=useCallback(async()=>{setLoading(true);try{const [d,v]=await Promise.all([fleetApi.drivers(),fleetApi.vehicles()]);setDrivers(d);setVehicles(v);setError(undefined)}catch(reason){setError(reason instanceof Error?reason.message:"Falha ao carregar frota.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function createDriver(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);setSaving(true);try{await fleetApi.createDriver({companyId:String(data.get("companyId")),name:String(data.get("name")),document:String(data.get("document")||"")||undefined});form.reset();setNotice("Motorista cadastrado.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Falha ao cadastrar motorista.")}finally{setSaving(false)}}
 async function createVehicle(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);setSaving(true);try{await fleetApi.createVehicle({companyId:String(data.get("companyId")),plate:String(data.get("plate")).toUpperCase()});form.reset();setNotice("Veículo cadastrado.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Falha ao cadastrar veículo.")}finally{setSaving(false)}}
 return <div className="page"><div className="page-heading"><div><p className="eyebrow">CADASTROS OPERACIONAIS</p><h1>Motoristas e veículos</h1><p>Registros reais e isolados por empresa.</p></div><button className="button secondary" onClick={()=>void load()} disabled={loading}>↻ Atualizar</button></div>
 {error&&<div className="feedback error"><span>{error}</span><button onClick={()=>setError(undefined)}>×</button></div>}{notice&&<div className="feedback success"><span>{notice}</span><button onClick={()=>setNotice(undefined)}>×</button></div>}
 <section className="dashboard-grid"><article className="panel"><div className="panel-heading"><div><h2>Novo motorista</h2><p>O UUID gerado deve ser enviado no claim OIDC driver_id.</p></div></div><form className="activity-form" onSubmit={createDriver}><label>Empresa (UUID)<input name="companyId" required pattern="[0-9a-fA-F-]{36}"/></label><label>Nome<input name="name" required minLength={3} maxLength={160}/></label><label>Documento<input name="document" maxLength={120}/></label><button className="button primary" disabled={saving}>Cadastrar motorista</button></form></article>
 <article className="panel"><div className="panel-heading"><div><h2>Novo veículo</h2><p>Placa no padrão Mercosul ou anterior.</p></div></div><form className="activity-form" onSubmit={createVehicle}><label>Empresa (UUID)<input name="companyId" required pattern="[0-9a-fA-F-]{36}"/></label><label>Placa<input name="plate" required pattern="[A-Za-z]{3}[0-9][A-Za-z0-9][0-9]{2}" maxLength={7}/></label><button className="button primary" disabled={saving}>Cadastrar veículo</button></form></article></section>
 <section className="dashboard-grid"><article className="panel recent"><div className="panel-heading"><div><h2>Motoristas</h2><p>{drivers.length} cadastrados</p></div></div><div className="table-wrap"><table><thead><tr><th>Nome</th><th>Documento</th><th>UUID / claim</th></tr></thead><tbody>{drivers.map(item=><tr key={item.id}><td><b>{item.name}</b></td><td>{item.document||"—"}</td><td><span className="uuid-value">{item.id}</span></td></tr>)}</tbody></table>{!loading&&!drivers.length&&<div className="empty">Nenhum motorista cadastrado.</div>}</div></article>
 <article className="panel recent"><div className="panel-heading"><div><h2>Veículos</h2><p>{vehicles.length} cadastrados</p></div></div><div className="table-wrap"><table><thead><tr><th>Placa</th><th>UUID</th></tr></thead><tbody>{vehicles.map(item=><tr key={item.id}><td><b>{item.plate}</b></td><td><span className="uuid-value">{item.id}</span></td></tr>)}</tbody></table>{!loading&&!vehicles.length&&<div className="empty">Nenhum veículo cadastrado.</div>}</div></article></section></div>
}
