import Link from "next/link";
import { StatusBadge } from "@/components/status-badge";
import { activities, drivers, metrics } from "@/lib/mock-data";

export default function Dashboard() {
  return <div className="page">
    <div className="page-heading"><div><p className="eyebrow">QUARTA-FEIRA, 15 DE JULHO</p><h1>Olá, Lucas <span>👋</span></h1><p>Acompanhe o que está acontecendo na sua operação hoje.</p></div><div className="heading-actions"><button className="button secondary">↗ Exportar</button><Link href="/operacoes" className="button primary">＋ Nova atividade</Link></div></div>
    <section className="metric-grid">{metrics.map((item, index) => <article className={`metric-card ${item.tone}`} key={item.label}><div className="metric-top"><span className="metric-icon">{["▦","✓","↗","!"][index]}</span>{item.trend && <small>{item.trend}</small>}</div><strong>{item.value}</strong><h3>{item.label}</h3><p>{item.detail}</p></article>)}</section>
    <section className="dashboard-grid">
      <article className="panel chart-panel"><div className="panel-heading"><div><h2>Ritmo da operação</h2><p>Atividades concluídas por hora</p></div><select aria-label="Período"><option>Hoje</option><option>7 dias</option></select></div><div className="chart"><div className="ylabels"><span>40</span><span>30</span><span>20</span><span>10</span><span>0</span></div><svg viewBox="0 0 700 190" preserveAspectRatio="none" aria-label="Gráfico de atividades"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#326bff" stopOpacity=".24"/><stop offset="1" stopColor="#326bff" stopOpacity="0"/></linearGradient></defs><path className="gridline" d="M0 18H700M0 57H700M0 96H700M0 135H700M0 174H700"/><path fill="url(#area)" d="M0 165 C70 158,80 140,140 145 S220 120,280 125 S350 95,420 105 S490 54,560 70 S630 35,700 28 L700 190 L0 190Z"/><path className="chart-line" d="M0 165 C70 158,80 140,140 145 S220 120,280 125 S350 95,420 105 S490 54,560 70 S630 35,700 28"/></svg><div className="xlabels"><span>06h</span><span>08h</span><span>10h</span><span>12h</span><span>14h</span><span>16h</span><span>18h</span></div></div></article>
      <article className="panel drivers-panel"><div className="panel-heading"><div><h2>Motoristas em campo</h2><p>18 ativos agora</p></div><Link href="/mapa">Ver mapa</Link></div><div className="driver-list">{drivers.slice(0,4).map(driver => <div className="driver" key={driver.id}><span className="avatar">{driver.initials}<i className={driver.status === "Disponível" ? "available" : ""}/></span><div><b>{driver.name}</b><small>{driver.vehicle}</small></div><span className="driver-state">{driver.lastUpdate}</span></div>)}</div></article>
    </section>
    <section className="panel recent"><div className="panel-heading"><div><h2>Atividades recentes</h2><p>Últimas atualizações da operação</p></div><Link href="/operacoes">Ver todas →</Link></div><div className="table-wrap"><table><thead><tr><th>Atividade</th><th>Cliente</th><th>Motorista</th><th>Agendamento</th><th>Status</th><th></th></tr></thead><tbody>{activities.slice(0,5).map(activity => <tr key={activity.id}><td><b>{activity.reference}</b><small>{activity.kind}</small></td><td><b>{activity.customer}</b><small>{activity.address}</small></td><td>{activity.driver}</td><td>{activity.scheduledAt}</td><td><StatusBadge status={activity.status}/></td><td>•••</td></tr>)}</tbody></table></div></section>
  </div>;
}
