import { createContext, PropsWithChildren, useContext, useEffect, useMemo, useRef, useState } from 'react';
import { Platform } from 'react-native';
import type { Activity, ActivityStatus } from '../domain/activity'; import { transitionActivity } from '../domain/activity';
import type { LocalStore, LocationTracker } from '../offline/contracts'; import { Outbox } from '../offline/outbox'; import { createLocalStore } from '../offline/storeFactory';
import type { EvidenceManifest } from '../evidence/types'; import { LocalEvidenceUploadQueue } from '../evidence/uploadQueue'; import { createLocationTracker } from '../location/trackerFactory'; import type { LocationPermission } from '../location/types';
import { ApiSyncClient, apiConfigFromEnv } from '../sync/apiSyncClient'; import { SyncCoordinator } from '../sync/coordinator';
import { authConfigFromEnv } from '../auth/config'; import { OidcSessionManager } from '../auth/sessionManager'; import type { TokenSet, TokenVault } from '../auth/types'; import { createTokenVault } from '../auth/vault';
interface AppState { signedIn: boolean; journeyActive: boolean; locationPermission: LocationPermission; activities: Activity[]; pending: number; syncing: boolean; conflicts: number; syncError?: string; devAuthBypass: boolean; demoLogin(): void; completeOidcLogin(tokens: TokenSet): Promise<void>; logout(): Promise<void>; toggleJourney(): Promise<void>; synchronize(): Promise<void>; advance(id: string, status: ActivityStatus): Promise<void>; submitEvidence(manifest: EvidenceManifest): Promise<void>; }
const Context = createContext<AppState | null>(null);
export function AppProvider({ children }: PropsWithChildren) {
  const authConfig = authConfigFromEnv(); const [signedIn, setSignedIn] = useState(false); const [journeyActive, setJourneyActive] = useState(false); const [locationPermission, setLocationPermission] = useState<LocationPermission>('unknown');
  const [activities, setActivities] = useState<Activity[]>([]); const [pending, setPending] = useState(0); const [syncing, setSyncing] = useState(false); const [conflicts, setConflicts] = useState(0); const [syncError, setSyncError] = useState<string>();
  const storeRef = useRef<LocalStore | null>(null); const trackerRef = useRef<LocationTracker | null>(null); const vaultRef = useRef<TokenVault | null>(null); const sessionRef = useRef<OidcSessionManager | null>(null);
  useEffect(() => { let active = true; void (async () => { const vault = createTokenVault(Platform.OS); vaultRef.current = vault; sessionRef.current = new OidcSessionManager(authConfig, vault); const tokens = await vault.loadTokens(); const store = await createLocalStore(Platform.OS); await store.initialize(); const persisted = await store.listActivities(); if (!active) return; setSignedIn(authConfig.devBypass || Boolean(tokens)); storeRef.current = store; trackerRef.current = await createLocationTracker(Platform.OS, store); setActivities(persisted); setPending((await store.pendingCommands()).length); setJourneyActive(Boolean(await store.getMetadata('activeJourneyId'))); })(); return () => { active = false; }; }, []);
  const value = useMemo<AppState>(() => ({ signedIn, journeyActive, locationPermission, activities, pending, syncing, conflicts, syncError, devAuthBypass: authConfig.devBypass,
    demoLogin: () => { if (authConfig.devBypass) setSignedIn(true); }, completeOidcLogin: async (tokens) => { await vaultRef.current?.saveTokens(tokens); setSignedIn(true); }, logout: async () => { await sessionRef.current?.logout(); setSignedIn(false); setJourneyActive(false); },
    synchronize: async () => { const store = storeRef.current; const vault = vaultRef.current; if (!store || !vault || syncing) return; setSyncing(true); try { const accessToken = authConfig.devBypass ? undefined : await sessionRef.current?.getValidAccessToken(); const config = apiConfigFromEnv(accessToken, await vault.getOrCreateDeviceId()); if (!config) throw new Error('Configuração de API/autenticação ausente'); const report = await new SyncCoordinator(store, new ApiSyncClient(config)).synchronize(); setPending(report.pending); setActivities(await store.listActivities()); setConflicts(report.conflicts); setSyncError(report.evidenceError); } catch (error) { setSyncError(error instanceof Error ? error.message : 'Falha de autenticação'); if (!authConfig.devBypass && error instanceof Error && error.message === 'Sessão expirada') setSignedIn(false); } finally { setSyncing(false); } },
    toggleJourney: async () => { const tracker = trackerRef.current; if (!tracker) return; if (journeyActive) { await tracker.stopJourney(); setJourneyActive(false); return; } const result = await tracker.startJourney(`journey-${new Date().toISOString().slice(0, 10)}`); setLocationPermission(result.permission); setJourneyActive(result.active); },
    submitEvidence: async (manifest) => { const store = storeRef.current; if (!store) throw new Error('Armazenamento ainda não inicializado'); await store.saveEvidenceManifest(manifest); await new LocalEvidenceUploadQueue(store).enqueue(manifest); setPending((await store.pendingCommands()).length); },
    advance: async (id, status) => { const current = activities.find((item) => item.id === id); if (!current) return; const updated = transitionActivity(current, status); const next = activities.map((item) => item.id === id ? updated : item); setActivities(next); const store = storeRef.current; if (store) { await store.saveActivities(next); await new Outbox(store).add('activity.status.' + status, id, { status }); setPending((await store.pendingCommands()).length); } },
  }), [signedIn, journeyActive, locationPermission, activities, pending, syncing, conflicts, syncError]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useApp() { const value = useContext(Context); if (!value) throw new Error('useApp deve estar dentro de AppProvider'); return value; }
