import { Camera, CameraView } from 'expo-camera';
import { Stack, useLocalSearchParams } from 'expo-router';
import { useRef, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { persistCameraPhoto, persistSignature } from '../../src/evidence/files';
import { DEFAULT_EVIDENCE_POLICY, validateEvidence } from '../../src/evidence/policy';
import type { EvidenceFile, EvidenceManifest, SignaturePoint } from '../../src/evidence/types';
import { useApp } from '../../src/session/AppContext';
import { SignaturePad } from '../../src/ui/SignaturePad';
import { colors } from '../../src/ui/theme';
const CompatibleCameraView = CameraView as unknown as React.ComponentType<any>;
export default function EvidenceScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { submitEvidence } = useApp(); const camera = useRef<CameraView>(null);
  const [receiverName, setReceiverName] = useState(''); const [document, setDocument] = useState(''); const [photo, setPhoto] = useState<EvidenceFile>(); const [signature, setSignature] = useState<SignaturePoint[]>([]); const [cameraOpen, setCameraOpen] = useState(false); const [errors, setErrors] = useState<string[]>([]); const [queued, setQueued] = useState(false);
  async function openCamera() { const permission = await Camera.requestCameraPermissionsAsync(); if (!permission.granted) { setErrors(['A permissão da câmera é necessária para capturar a evidência.']); return; } setCameraOpen(true); }
  async function capture() { const result = await camera.current?.takePictureAsync({ quality: 0.75, exif: false }); if (!result) return; setPhoto(await persistCameraPhoto(id, result.uri)); setCameraOpen(false); }
  async function submit() { const now = new Date().toISOString(); const signatureFile: EvidenceFile = await persistSignature(id, signature); const manifest: EvidenceManifest = { id: `${id}-completion`, activityId: id, receiver: { name: receiverName.trim(), document: document.trim() }, files: [...(photo ? [photo] : []), signatureFile], status: 'local', updatedAt: now }; const validation = validateEvidence(manifest, DEFAULT_EVIDENCE_POLICY); setErrors(validation); if (validation.length) return; await submitEvidence(manifest); setQueued(true); }
  if (cameraOpen) return <View style={styles.cameraPage}><Stack.Screen options={{ title: 'Capturar foto' }} /><CompatibleCameraView ref={camera} style={styles.camera} facing="back" /><Pressable style={styles.capture} onPress={capture}><Text style={styles.primaryText}>Capturar foto</Text></Pressable><Pressable onPress={() => setCameraOpen(false)}><Text style={styles.cancel}>Cancelar</Text></Pressable></View>;
  if (queued) return <View style={styles.pending}><Stack.Screen options={{ title: 'Conclusão pendente' }} /><Text style={styles.pendingTitle}>Evidências salvas</Text><Text style={styles.pendingText}>A atividade permanecerá pendente até o servidor confirmar o recebimento das evidências.</Text><View style={styles.badge}><Text style={styles.badgeText}>Aguardando sincronização</Text></View></View>;
  return <ScrollView contentContainerStyle={styles.page}><Stack.Screen options={{ title: 'Concluir atividade' }} /><Text style={styles.title}>Comprovante de operação</Text><Text style={styles.copy}>Preencha os dados e colete as evidências obrigatórias. A galeria não é permitida.</Text>
    <Text style={styles.label}>Nome do recebedor</Text><TextInput style={styles.input} value={receiverName} onChangeText={setReceiverName} placeholder="Nome completo" />
    <Text style={styles.label}>CPF/RG ou documento</Text><TextInput style={styles.input} value={document} onChangeText={setDocument} placeholder="Documento" />
    <Text style={styles.label}>Foto</Text>{photo?.localUri ? <Image source={{ uri: photo.localUri }} style={styles.preview} /> : null}<Pressable style={styles.secondary} onPress={openCamera}><Text style={styles.secondaryText}>{photo ? 'Refazer pela câmera' : 'Abrir câmera'}</Text></Pressable>
    <Text style={styles.label}>Assinatura</Text><SignaturePad value={signature} onChange={setSignature} />
    {errors.map((error) => <Text key={error} style={styles.error}>{error}</Text>)}<Pressable style={styles.primary} onPress={submit}><Text style={styles.primaryText}>Salvar e solicitar confirmação</Text></Pressable>
  </ScrollView>;
}
const styles = StyleSheet.create({ page: { padding: 20, paddingBottom: 45 }, title: { color: colors.ink, fontSize: 27, fontWeight: '800' }, copy: { color: colors.muted, lineHeight: 21, marginTop: 8, marginBottom: 22 }, label: { color: colors.ink, fontWeight: '700', marginTop: 14, marginBottom: 7 }, input: { backgroundColor: '#FFF', borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 14, fontSize: 16 }, secondary: { backgroundColor: colors.primarySoft, borderRadius: 12, padding: 14, alignItems: 'center' }, secondaryText: { color: colors.primary, fontWeight: '800' }, preview: { height: 190, borderRadius: 12, marginBottom: 10 }, primary: { backgroundColor: colors.primary, borderRadius: 13, padding: 16, alignItems: 'center', marginTop: 18 }, primaryText: { color: '#FFF', fontWeight: '800' }, error: { color: colors.danger, marginTop: 7 }, cameraPage: { flex: 1, backgroundColor: '#000', paddingBottom: 30 }, camera: { flex: 1 }, capture: { margin: 20, backgroundColor: colors.primary, padding: 17, borderRadius: 14, alignItems: 'center' }, cancel: { color: '#FFF', textAlign: 'center' }, pending: { flex: 1, padding: 30, alignItems: 'center', justifyContent: 'center' }, pendingTitle: { fontSize: 28, color: colors.ink, fontWeight: '800' }, pendingText: { color: colors.muted, textAlign: 'center', lineHeight: 22, marginTop: 12 }, badge: { backgroundColor: '#FFF3D6', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 9, marginTop: 20 }, badgeText: { color: '#8A5B00', fontWeight: '700' } });
